# Generated by Django 6.0.2 on 2026-02-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Documents', 'Documents'), ('Personal Effects', 'Personal Effects'), ('Others', 'Others')], max_length=50)),
                ('status', models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found')], max_length=10)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='items/')),
            ],
        ),
    ]
