# Generated by Django 6.0.2 on 2026-02-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_lost',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='time_lost',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
    ]
